exclude_patterns:
  - "Tests/"
  - "Src/OverwatchArcade.API/AutoMapperProfile.cs"
  - "Src/OverwatchArcade.API/DependencyInjection.cs"
  - "Src/OverwatchArcade.Persistence/Migrations/"
  - "Src/OverwatchArcade.Persistence/EntityConfiguration/"
