exclude_patterns:
  - "Src/OverwatchArcade.Tests"
  - "Src/OverwatchArcade.API/AutoMapperProfile.cs"
  - "Src/OverwatchArcade.Persistence/Migrations/"
  - "Src/OverwatchArcade.Persistence/EntityConfiguration/"
